language: haxe
dist: xenial
haxe:
  - development

install:
  - haxelib install -always build.hxml
  - haxelib list
  - haxelib git dox https://github.com/HaxeFoundation/dox

script:
  - haxe build.hxml
  - haxe doc.hxml

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: bin/doc
  on:
    branch: master
