name: gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: krdlab/setup-haxe@v1.1.2
    - run: haxelib install -always build.hxml
    - run: haxelib git dox https://github.com/HaxeFoundation/dox
    - run: haxe doc.hxml
    - uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: out
