name: CI

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1.1.2
    - name: Build Lib
      run: |
        haxelib install -always build.hxml
        haxe build.hxml
    - name: Build Docs
      run: |
        haxelib git dox https://github.com/HaxeFoundation/dox
        haxe doc.hxml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: out
      if: github.ref == 'refs/heads/master'
